name: CI pipeline

on:
  push:
   branches: [ main ]
   pull_request:
   branches: [ main ]
   workflow_dispatch:
  

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_name: test-image
  

    steps:
      - uses: actions/checkout@v5
   
      - uses: actions/setup-python@v4
        with:
           python-version: '3.11'
      - run: pip install -r requirements.txt  
      - run: pytest    
      - run: docker --version
      - run: echo "this is my second workflow"
    
      - run: cat test.txt
      
      
  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      APP_name: build-image

    steps:
      - uses: actions/checkout@v5
      - run: docker build -t test-image . 
      - run: echo "build is running"
      