name: CI pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
  

    steps:
      - run: docker --version
      - run: echo "this is my second workflow"
      - uses: actions/checkout@v4
      - run: cat test.txt
      
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - run: docker --version
      - run: echo "build is running"
      